# Generated by Django 5.0.3 on 2024-03-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_item_seller_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='highest_bid',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
            preserve_default=False,
        ),
    ]
