# Generated by Django 5.0.3 on 2024-03-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auctionitem_highest_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='highest_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
